version: 2

models:
  - name: stg_loans
    columns:
      - name: loan_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]
      - name: loan_status
        tests:
          - accepted_values:
              arguments:
                values: ['active', 'delinquent', 'charged_off']
      - name: pd_score
        tests: [not_null]
      - name: ifrs9_stage
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3]

  - name: stg_customers
    columns:
      - name: customer_id
        tests: [unique, not_null]
      - name: employment_status
        tests:
          - accepted_values:
              arguments:
                values: ['employed', 'self_employed', 'unemployed', 'retired']