name: CI/CD Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pre-commit dbt-core dbt-snowflake
      - run: pre-commit run --all-files
      - run: dbt compile --project-dir dbt_project
      - run: dbt test --project-dir dbt_project
      - name: Check dbt run_results
        run: |
          if [ -f dbt_project/target/run_results.json ]; then
            echo "✅ dbt test past"
          else
            echo "❌ failed to generate run_results"
            exit 1
          fi